[package]
name = "covjece-ne-ljuti-se"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
inline_colorization = "0.1.5"
rand = "0.8.5"
